name: app check

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]


jobs:
  elixir-check:
    runs-on: ubuntu-24.04
    env:
      ImageOS: ubuntu24
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          elixir-version: '1.16.3'
      - run: mix deps.get
      - run: mix test