name: app check

on: push

jobs:
  elixir-check:
    runs-on: ubuntu-latest
    services:
      db:
        image: bitnami/postgresql:16
        ports: ['5432:5432']
        env:
          POSTGRESQL_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.17.5
        with:
          otp-version: '25'
          elixir-version: '1.16.3'
      - run: mix deps.get
      - run: mix test